# for Travis CI
language: python
python:
  - "3.7"
os:
  # Travis doesn't support testing Python projects on macOS, as of today
  - linux

script:
  - sanity/check-runtest.sh
branches:
  only:
    - master
